// Run with: npx prisma db seed

import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { HashService } from '../common/hash/hash.service';
import {
  AuctionType,
  ChecklistSeverity,
  FuelType,
  Prisma,
  PrismaClient,
  TransmissionType,
  VehicleDamageType,
  VehicleStatus,
  VehicleType,
} from '../../generated/prisma/client';

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({ adapter });

const seedUsers = [
  {
    name: 'Admin',
    email: 'admin@email.com',
    password: '123456',
    role: 'admin',
  },
  {
    name: 'Erick Prado',
    email: 'erickprado@email.com',
    password: '123456',
    role: 'user',
  },
] satisfies Array<{
  name: string;
  email: string;
  password: string;
  role: 'admin' | 'user';
}>;

const seedVehicles = [
  {
    plate: 'QWE1A23',
    brand: 'Honda',
    model: 'Civic',
    version: 'Touring 1.5 Turbo',
    yearManufacture: 2021,
    yearModel: 2022,
    color: 'Preto',
    fuelType: FuelType.FLEX,
    transmission: TransmissionType.AUTOMATIC,
    type: VehicleType.CAR,
    mileage: 45200,
    fipeCode: '014082-0',
    fipeValue: new Prisma.Decimal('145000.00'),
    marketValue: new Prisma.Decimal('138000.00'),
    auctioneer: 'Copart',
    auctionType: AuctionType.BANK,
    sourceUrl: 'https://copart.com/lote/123',
    eventDate: new Date('2026-05-01T10:00:00.000Z'),
    city: 'Campo Grande',
    state: 'MS',
    yardAddress: 'Av. Gury Marques, 5500',
    auctionInitialBid: new Prisma.Decimal('85000.00'),
    auctionCurrentBid: new Prisma.Decimal('92000.00'),
    damageType: VehicleDamageType.LOW_DAMAGE,
    status: VehicleStatus.ANALYZING,
    notes: 'Pequenos riscos no para-choque.',
  },
  {
    plate: 'BRA2B45',
    brand: 'Toyota',
    model: 'Corolla',
    version: 'XEi 2.0',
    yearManufacture: 2020,
    yearModel: 2021,
    color: 'Branco',
    fuelType: FuelType.FLEX,
    transmission: TransmissionType.CVT,
    type: VehicleType.CAR,
    mileage: 62000,
    fipeCode: '002184-9',
    fipeValue: new Prisma.Decimal('128000.00'),
    marketValue: new Prisma.Decimal('124000.00'),
    auctioneer: 'Freitas Leiloeiro',
    auctionType: AuctionType.JUDICIAL,
    sourceUrl: 'https://leilao.com/lote/456',
    eventDate: new Date('2026-05-02T10:00:00.000Z'),
    city: 'Dourados',
    state: 'MS',
    yardAddress: 'Rua Projetada A',
    auctionInitialBid: new Prisma.Decimal('72000.00'),
    auctionCurrentBid: new Prisma.Decimal('81000.00'),
    damageType: VehicleDamageType.NONE,
    status: VehicleStatus.ANALYZING,
    notes: 'Veiculo aparentemente integro.',
  },
  {
    plate: 'TES3C67',
    brand: 'Volkswagen',
    model: 'Golf GTI',
    version: '2.0 TSI',
    yearManufacture: 2015,
    yearModel: 2015,
    color: 'Vermelho',
    fuelType: FuelType.GASOLINE,
    transmission: TransmissionType.AUTOMATIC,
    type: VehicleType.CAR,
    mileage: 89000,
    fipeCode: '005340-6',
    fipeValue: new Prisma.Decimal('115000.00'),
    marketValue: new Prisma.Decimal('108000.00'),
    auctioneer: 'Sodre Santoro',
    auctionType: AuctionType.EXTRAJUDICIAL,
    sourceUrl: 'https://sodresantoro.com/lote/789',
    eventDate: new Date('2026-05-03T10:00:00.000Z'),
    city: 'Sao Paulo',
    state: 'SP',
    yardAddress: 'Rodovia Anhanguera KM 25',
    auctionInitialBid: new Prisma.Decimal('65000.00'),
    auctionCurrentBid: new Prisma.Decimal('70000.00'),
    damageType: VehicleDamageType.NONE,
    status: VehicleStatus.ANALYZING,
    notes: 'Necessario troca dos pneus.',
  },
  {
    plate: 'FOX4D89',
    brand: 'Ford',
    model: 'Ranger',
    version: 'Limited 3.2',
    yearManufacture: 2019,
    yearModel: 2020,
    color: 'Prata',
    fuelType: FuelType.DIESEL,
    transmission: TransmissionType.AUTOMATIC,
    type: VehicleType.TRUCK,
    mileage: 71000,
    fipeCode: '003269-7',
    fipeValue: new Prisma.Decimal('189000.00'),
    marketValue: new Prisma.Decimal('181000.00'),
    auctioneer: 'VIP Leiloes',
    auctionType: AuctionType.INSURANCE,
    sourceUrl: 'https://vipleiloes.com/lote/101',
    eventDate: new Date('2026-05-04T10:00:00.000Z'),
    city: 'Cuiaba',
    state: 'MT',
    yardAddress: 'Distrito Industrial',
    auctionInitialBid: new Prisma.Decimal('105000.00'),
    auctionCurrentBid: new Prisma.Decimal('118000.00'),
    damageType: VehicleDamageType.LOW_DAMAGE,
    status: VehicleStatus.PURCHASED,
    notes: 'Sinistro leve frontal.',
  },
  {
    plate: 'BMW5E12',
    brand: 'BMW',
    model: '320i',
    version: 'GP 2.0 Turbo',
    yearManufacture: 2022,
    yearModel: 2023,
    color: 'Azul',
    fuelType: FuelType.FLEX,
    transmission: TransmissionType.AUTOMATIC,
    type: VehicleType.CAR,
    mileage: 15000,
    fipeCode: '009876-1',
    fipeValue: new Prisma.Decimal('289000.00'),
    marketValue: new Prisma.Decimal('280000.00'),
    auctioneer: 'Copart',
    auctionType: AuctionType.BANK,
    sourceUrl: 'https://copart.com/lote/555',
    eventDate: new Date('2026-05-05T10:00:00.000Z'),
    city: 'Curitiba',
    state: 'PR',
    yardAddress: 'Rua Industrial 300',
    auctionInitialBid: new Prisma.Decimal('180000.00'),
    auctionCurrentBid: new Prisma.Decimal('192000.00'),
    damageType: VehicleDamageType.OTHER,
    status: VehicleStatus.ANALYZING,
    notes: 'Sem chave.',
  },
] satisfies Omit<Prisma.VehicleUncheckedCreateInput, 'userId'>[];

const motorcycleChecklistItems = [
  [
    'Motor',
    'Compressao / fumaca / sopro',
    '3200.00',
    ChecklistSeverity.CRITICAL,
    false,
    true,
    10,
  ],
  [
    'Motor',
    'Cabecote / valvulas / comando',
    '1200.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    11,
  ],
  [
    'Motor',
    'Vazamentos do motor',
    '380.00',
    ChecklistSeverity.MEDIUM,
    false,
    true,
    12,
  ],
  [
    'Motor',
    'Sistema de arrefecimento',
    '450.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    13,
  ],
  [
    'Motor',
    'Injecao / TBI / ignicao',
    '550.00',
    ChecklistSeverity.MEDIUM,
    false,
    true,
    14,
  ],
  [
    'Motor',
    'Carter / tampa lateral / carcaca',
    '1100.00',
    ChecklistSeverity.HIGH,
    false,
    false,
    15,
  ],
  [
    'Transmissao',
    'Kit relacao (corrente/coroa/pinhao)',
    '180.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    20,
  ],
  [
    'Transmissao',
    'Kit de embreagem',
    '320.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    21,
  ],
  [
    'Transmissao',
    'Cabo / atuador da embreagem',
    '60.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    22,
  ],
  [
    'Transmissao',
    'Cambio / seletores / pedal',
    '900.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    23,
  ],
  [
    'Transmissao',
    'Retentores / vazamentos da transmissao',
    '220.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    24,
  ],
  [
    'Transmissao',
    'Cubo / campana / rolamentos da transmissao',
    '420.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    25,
  ],
  [
    'Pneus',
    'Pneu dianteiro',
    '220.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    30,
  ],
  ['Pneus', 'Pneu traseiro', '260.00', ChecklistSeverity.HIGH, false, true, 31],
  [
    'Pneus',
    'Camara de ar / valvulas',
    '45.00',
    ChecklistSeverity.LOW,
    true,
    false,
    32,
  ],
  [
    'Pneus',
    'Rodas / aros',
    '260.00',
    ChecklistSeverity.MEDIUM,
    true,
    false,
    33,
  ],
  [
    'Pneus',
    'Balanceamento / alinhamento de rodas',
    '60.00',
    ChecklistSeverity.LOW,
    true,
    false,
    34,
  ],
  [
    'Pneus',
    'Rolamentos de roda',
    '80.00',
    ChecklistSeverity.MEDIUM,
    true,
    false,
    35,
  ],
  [
    'Eletrica',
    'Bateria 12V',
    '240.00',
    ChecklistSeverity.MEDIUM,
    false,
    true,
    40,
  ],
  [
    'Eletrica',
    'Estator / regulador / retificador',
    '520.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    41,
  ],
  [
    'Eletrica',
    'Motor de partida / rele',
    '320.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    42,
  ],
  [
    'Eletrica',
    'Iluminacao / painel',
    '260.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    43,
  ],
  [
    'Eletrica',
    'Chicote / fusiveis / conectores',
    '320.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    44,
  ],
  [
    'Eletrica',
    'Sensores / painel de instrumentos',
    '450.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    45,
  ],
  [
    'Lataria',
    'Tanque de combustivel',
    '850.00',
    ChecklistSeverity.HIGH,
    false,
    false,
    50,
  ],
  [
    'Lataria',
    'Kit carenagem / laterais / rabeta',
    '650.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    51,
  ],
  [
    'Lataria',
    'Conjunto frontal / farol / suporte',
    '420.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    52,
  ],
  [
    'Lataria',
    'Retrovisores / manetes',
    '90.00',
    ChecklistSeverity.MEDIUM,
    true,
    true,
    53,
  ],
  [
    'Lataria',
    'Pedaleiras / suportes / escape',
    '420.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    54,
  ],
  [
    'Lataria',
    'Quadro / berco / soldas aparentes',
    '2500.00',
    ChecklistSeverity.CRITICAL,
    false,
    true,
    55,
  ],
  [
    'Interior/Comandos',
    'Banco / trava / base',
    '220.00',
    ChecklistSeverity.LOW,
    false,
    false,
    60,
  ],
  [
    'Interior/Comandos',
    'Painel / velocimetro',
    '350.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    61,
  ],
  [
    'Interior/Comandos',
    'Comutador de ignicao / chave',
    '320.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    62,
  ],
  [
    'Interior/Comandos',
    'Acelerador / manoplas / punhos',
    '80.00',
    ChecklistSeverity.LOW,
    false,
    false,
    63,
  ],
  [
    'Interior/Comandos',
    'Comando de embreagem / manete',
    '70.00',
    ChecklistSeverity.LOW,
    false,
    false,
    64,
  ],
  [
    'Interior/Comandos',
    'Comando de freio / pedal',
    '80.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    65,
  ],
  [
    'Suspensao',
    'Bengalas dianteiras',
    '520.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    70,
  ],
  [
    'Suspensao',
    'Mesas / caixa de direcao',
    '380.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    71,
  ],
  [
    'Suspensao',
    'Amortecedor(es) traseiro(s)',
    '360.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    72,
  ],
  [
    'Suspensao',
    'Balanca / buchas / quadro elastico',
    '150.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    73,
  ],
  [
    'Suspensao',
    'Alinhamento de chassi',
    '900.00',
    ChecklistSeverity.CRITICAL,
    false,
    true,
    74,
  ],
  [
    'Suspensao',
    'Rolamentos da direcao / rodas',
    '160.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    75,
  ],
  [
    'Freios',
    'Pastilhas dianteiras',
    '65.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    80,
  ],
  [
    'Freios',
    'Disco dianteiro',
    '180.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    81,
  ],
  [
    'Freios',
    'Sistema traseiro (lona/pastilha)',
    '120.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    82,
  ],
  [
    'Freios',
    'Fluido / mangueiras / flexiveis',
    '120.00',
    ChecklistSeverity.MEDIUM,
    false,
    true,
    83,
  ],
  [
    'Freios',
    'Pinca / cilindro mestre',
    '380.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    84,
  ],
  [
    'Freios',
    'ABS / CBS / sensor de roda',
    '480.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    85,
  ],
  [
    'Documentacao',
    'Transferencia / ATPV-e / CRV-CRLV',
    '380.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    90,
  ],
  [
    'Documentacao',
    'Vistoria / laudo / ECV',
    '160.00',
    ChecklistSeverity.MEDIUM,
    false,
    true,
    91,
  ],
  [
    'Documentacao',
    'Licenciamento em atraso',
    '260.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    92,
  ],
  [
    'Documentacao',
    'Debitos de IPVA / multas',
    '700.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    93,
  ],
  [
    'Documentacao',
    'Placa / suporte / lacre',
    '150.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    94,
  ],
  [
    'Documentacao',
    'Remarcacao chassi / motor / 2a via',
    '320.00',
    ChecklistSeverity.CRITICAL,
    false,
    true,
    95,
  ],
  [
    'Seguranca',
    'Quadro trincado / solda estrutural',
    '2600.00',
    ChecklistSeverity.CRITICAL,
    false,
    true,
    100,
  ],
  [
    'Seguranca',
    'Espelhos retrovisores obrigatorios',
    '90.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    101,
  ],
  [
    'Seguranca',
    'Farol / setas / lanterna / luz de placa',
    '250.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    102,
  ],
  ['Seguranca', 'Buzina', '45.00', ChecklistSeverity.MEDIUM, false, true, 103],
  [
    'Seguranca',
    'Escapamento / ruido / protetor termico',
    '320.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    104,
  ],
  [
    'Seguranca',
    'Recall pendente critico',
    '0.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    105,
  ],
  [
    'Inspecao/Outros',
    'Scanner / diagnostico eletronico',
    '100.00',
    ChecklistSeverity.MEDIUM,
    false,
    true,
    110,
  ],
  [
    'Inspecao/Outros',
    'Laudo cautelar / procedencia',
    '220.00',
    ChecklistSeverity.HIGH,
    false,
    true,
    111,
  ],
  [
    'Inspecao/Outros',
    'Sinais de enchente / oxidacao severa',
    '2200.00',
    ChecklistSeverity.CRITICAL,
    false,
    true,
    112,
  ],
  [
    'Inspecao/Outros',
    'Guincho / remocao',
    '180.00',
    ChecklistSeverity.MEDIUM,
    false,
    false,
    113,
  ],
  [
    'Inspecao/Outros',
    'Higienizacao / lavagem tecnica',
    '160.00',
    ChecklistSeverity.LOW,
    false,
    false,
    114,
  ],
  [
    'Inspecao/Outros',
    'Preparacao estetica para venda',
    '260.00',
    ChecklistSeverity.LOW,
    false,
    false,
    115,
  ],
] satisfies Array<
  [string, string, string, ChecklistSeverity, boolean, boolean, number]
>;

async function main() {
  const hashService = new HashService();

  const [adminPassword, userPassword] = await Promise.all([
    hashService.hash(seedUsers[0].password),
    hashService.hash(seedUsers[1].password),
  ]);

  const admin = await prisma.user.upsert({
    where: { email: seedUsers[0].email },
    update: {
      name: seedUsers[0].name,
      password: adminPassword,
      role: seedUsers[0].role,
      isActive: true,
    },
    create: {
      name: seedUsers[0].name,
      email: seedUsers[0].email,
      password: adminPassword,
      role: seedUsers[0].role,
      isActive: true,
    },
  });

  const user = await prisma.user.upsert({
    where: { email: seedUsers[1].email },
    update: {
      name: seedUsers[1].name,
      password: userPassword,
      role: seedUsers[1].role,
      isActive: true,
    },
    create: {
      name: seedUsers[1].name,
      email: seedUsers[1].email,
      password: userPassword,
      role: seedUsers[1].role,
      isActive: true,
    },
  });

  /**
   * Vehicles do not have a unique plate constraint in the schema, so the seed
   * checks by user + plate before inserting to stay idempotent.
   */
  for (const vehicle of seedVehicles) {
    const existingVehicle = await prisma.vehicle.findFirst({
      where: {
        userId: user.id,
        plate: vehicle.plate,
      },
      select: {
        id: true,
      },
    });

    if (!existingVehicle) {
      await prisma.vehicle.create({
        data: {
          ...vehicle,
          userId: user.id,
        },
      });
    }
  }

  const checklistTemplate = await prisma.checklistTemplate.findFirst({
    where: {
      name: 'Checklist padrao moto - leilao',
      vehicleType: VehicleType.MOTORCYCLE,
    },
    select: {
      id: true,
    },
  });

  const template =
    checklistTemplate ??
    (await prisma.checklistTemplate.create({
      data: {
        name: 'Checklist padrao moto - leilao',
        vehicleType: VehicleType.MOTORCYCLE,
        isActive: true,
      },
      select: {
        id: true,
      },
    }));

  /**
   * The checklist items are reference data. Replacing them on every seed keeps
   * local/dev databases synchronized with this source file.
   */
  await prisma.$transaction([
    prisma.checklistTemplateItem.deleteMany({
      where: {
        templateId: template.id,
      },
    }),
    prisma.checklistTemplateItem.createMany({
      data: motorcycleChecklistItems.map(
        ([
          category,
          name,
          defaultEstimatedCost,
          severity,
          requiresQuantity,
          isRequired,
          order,
        ]) => ({
          templateId: template.id,
          category,
          name,
          defaultEstimatedCost,
          severity,
          requiresQuantity,
          isRequired,
          order,
        }),
      ),
    }),
  ]);

  console.log('Seed executado com sucesso');
  console.log(`Admin: ${admin.email}`);
  console.log(`Usuario: ${user.email}`);
  console.log(`Veiculos criados/verificados: ${seedVehicles.length}`);
  console.log(`Itens do checklist criados: ${motorcycleChecklistItems.length}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
